apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"policy/v1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"labels":{"k8s-app":"calico-kube-controllers"},"name":"calico-kube-controllers","namespace":"kube-system"},"spec":{"maxUnavailable":1,"selector":{"matchLabels":{"k8s-app":"calico-kube-controllers"}}}}
  creationTimestamp: "2023-08-25T19:21:58Z"
  generation: 1
  labels:
    k8s-app: calico-kube-controllers
  name: calico-kube-controllers
  namespace: kube-system
  resourceVersion: "3120029"
  uid: 3b7135f5-08e3-4486-9aa6-47f90b19a1a1
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      k8s-app: calico-kube-controllers
status:
  conditions:
  - lastTransitionTime: "2023-09-27T18:42:18Z"
    message: ""
    observedGeneration: 1
    reason: SufficientPods
    status: "True"
    type: DisruptionAllowed
  currentHealthy: 1
  desiredHealthy: 0
  disruptionsAllowed: 1
  expectedPods: 1
  observedGeneration: 1
