apiVersion: v1
data:
  localRegistryHosting.v1: |
    help: "https://microk8s.io/docs/registry-built-in"
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"localRegistryHosting.v1":"help: \"https://microk8s.io/docs/registry-built-in\"\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"local-registry-hosting","namespace":"kube-public"}}
  creationTimestamp: "2023-08-25T19:22:13Z"
  name: local-registry-hosting
  namespace: kube-public
  resourceVersion: "188"
  uid: 8a03e516-759e-42aa-9473-d6bb8d47031c
