apiVersion: v1
data:
  since: "2023-08-25"
kind: ConfigMap
metadata:
  creationTimestamp: "2023-08-25T19:21:57Z"
  name: kube-apiserver-legacy-service-account-token-tracking
  namespace: kube-system
  resourceVersion: "38"
  uid: 813e519f-71c8-44c6-bf7f-33088fd41f88
