apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2023-08-25T19:22:03Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "100"
  uid: d630e283-b33e-440b-a1cd-8a8f0d86367a
spec:
  clusterIP: 10.152.183.1
  clusterIPs:
  - 10.152.183.1
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 16443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
