apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: "2023-09-12T19:16:12Z"
  name: leader-locking-nfs-client-provisioner
  namespace: default
  resourceVersion: "234704"
  uid: a799fe41-104f-4619-9982-8c78b088d6fe
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
