apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: nextcloud
    meta.helm.sh/release-namespace: default
  creationTimestamp: "2023-09-12T20:51:11Z"
  labels:
    app.kubernetes.io/managed-by: Helm
  name: nextcloud-serviceaccount
  namespace: default
  resourceVersion: "246665"
  uid: 41c375e3-4f0e-4336-b108-49a45f010ad1
