apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ConfigMap","metadata":{"annotations":{},"name":"nginx-load-balancer-microk8s-conf","namespace":"ingress"}}
  creationTimestamp: "2023-09-12T15:19:35Z"
  name: nginx-load-balancer-microk8s-conf
  namespace: ingress
  resourceVersion: "210403"
  uid: 91fe03e8-761c-4e0d-88c9-f04ccde8f031
