apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: "2023-09-12T19:16:12Z"
  name: leader-locking-nfs-client-provisioner
  namespace: default
  resourceVersion: "234705"
  uid: 59843e25-2051-496e-8299-87710f9b9872
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leader-locking-nfs-client-provisioner
subjects:
- kind: ServiceAccount
  name: nfs-client-provisioner
  namespace: default
