apiVersion: v1
kind: Endpoints
metadata:
  creationTimestamp: "2023-09-12T20:51:17Z"
  labels:
    app.kubernetes.io/component: app
    app.kubernetes.io/instance: nextcloud
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: nextcloud
    helm.sh/chart: nextcloud-4.3.1
  name: nextcloud
  namespace: default
  resourceVersion: "3120041"
  uid: dc0ebab8-c7a0-494c-9a14-eb75b95f5891
subsets:
- notReadyAddresses:
  - ip: 10.1.104.116
    nodeName: sve15136cn
    targetRef:
      kind: Pod
      name: nextcloud-694d5dbb6d-b9l4w
      namespace: default
      uid: 27009d2d-d0a9-46b0-9e86-9a3ac5c29333
  ports:
  - name: http
    port: 80
    protocol: TCP
