apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: csi-driver-nfs
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-09-12T18:26:37Z"
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: v4.4.0
    helm.sh/chart: csi-driver-nfs-v4.4.0
  name: csi-nfs-controller-sa
  namespace: kube-system
  resourceVersion: "228578"
  uid: 92de6cee-aff0-4d68-b62c-fb8bea4987f2
