apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-08-25T19:22:19Z"
  name: default
  namespace: kube-system
  resourceVersion: "250"
  uid: f86949dc-340b-4e1b-af3a-cfe9067f2776
