apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-08-25T19:22:13Z"
  name: endpointslice-controller
  namespace: kube-system
  resourceVersion: "184"
  uid: 3df3f4a1-1c72-461f-ac32-37720e411f32
