apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-08-25T19:22:08Z"
  name: ephemeral-volume-controller
  namespace: kube-system
  resourceVersion: "141"
  uid: 39f79400-03f7-4541-b562-2bb0c2d37561
