apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-08-25T19:22:07Z"
  name: pvc-protection-controller
  namespace: kube-system
  resourceVersion: "135"
  uid: 0718c052-3577-4121-aaf5-104717fdc969
