apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: csi-driver-nfs
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-09-12T18:26:37Z"
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: v4.4.0
    helm.sh/chart: csi-driver-nfs-v4.4.0
  name: snapshot-controller
  namespace: kube-system
  resourceVersion: "228580"
  uid: 6c93d46f-37fe-4829-9eda-474cfbb31b94
