apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2023-08-25T19:22:09Z"
  name: statefulset-controller
  namespace: kube-system
  resourceVersion: "156"
  uid: 556e72fd-7617-4c0f-85c8-2c8decb3041f
