apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    meta.helm.sh/release-name: csi-driver-nfs
    meta.helm.sh/release-namespace: kube-system
  creationTimestamp: "2023-09-12T18:26:42Z"
  labels:
    app.kubernetes.io/instance: csi-driver-nfs
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: csi-driver-nfs
    app.kubernetes.io/version: v4.4.0
    helm.sh/chart: csi-driver-nfs-v4.4.0
  name: snapshot-controller-leaderelection
  namespace: kube-system
  resourceVersion: "228606"
  uid: 186f9f95-7521-4136-bdee-76c53f3e9a9b
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: snapshot-controller-leaderelection
subjects:
- kind: ServiceAccount
  name: snapshot-controller
