apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"name":"nginx-ingress-microk8s","namespace":"ingress"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"nginx-ingress-microk8s-role"},"subjects":[{"kind":"ServiceAccount","name":"nginx-ingress-microk8s-serviceaccount"}]}
  creationTimestamp: "2023-09-12T15:19:35Z"
  name: nginx-ingress-microk8s
  namespace: ingress
  resourceVersion: "210401"
  uid: 415268a4-c86f-4299-83e3-ff79d5a6b592
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-ingress-microk8s-role
subjects:
- kind: ServiceAccount
  name: nginx-ingress-microk8s-serviceaccount
