apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"name":"nginx-ingress","namespace":"nginx-ingress"}}
  creationTimestamp: "2023-09-08T11:39:05Z"
  name: nginx-ingress
  namespace: nginx-ingress
  resourceVersion: "138369"
  uid: 3309e7aa-2ec0-4d46-99dc-607f6fb05520
