apiVersion: v1
kind: Endpoints
metadata:
  annotations:
    endpoints.kubernetes.io/last-change-trigger-time: "2023-09-27T18:41:19Z"
  creationTimestamp: "2023-08-25T19:22:15Z"
  labels:
    addonmanager.kubernetes.io/mode: Reconcile
    k8s-app: kube-dns
    kubernetes.io/cluster-service: "true"
    kubernetes.io/name: CoreDNS
  name: kube-dns
  namespace: kube-system
  resourceVersion: "3119949"
  uid: 56741875-c636-4361-aa89-8a110637f418
subsets:
- addresses:
  - ip: 10.1.104.112
    nodeName: sve15136cn
    targetRef:
      kind: Pod
      name: coredns-864597b5fd-84gjh
      namespace: kube-system
      uid: 0d7edcdc-8af1-4502-b521-3bcf651155a8
  ports:
  - name: dns-tcp
    port: 53
    protocol: TCP
  - name: dns
    port: 53
    protocol: UDP
  - name: metrics
    port: 9153
    protocol: TCP
